"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux';
import store from '@/redux/store'; // Import your Redux stor
const inter = Inter({ subsets: ['latin'] })

//export const metadata: Metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
//}
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

import Hero from '@/components/Hero'
import Demo from '@/components/Demo'
import React, { useState } from 'react';
import Link from 'next/link'
// import { createContext,useContext } from 'react';
import { MyProvider } from '@/context/MyContext';


// const UserContext = createContext(null)

export default function RootLayout({children,}: { children: React.ReactNode}) {
  
    return (
      <html lang='en'>
      {/* <head >
      </head> */}
        <body>
          {/* <Provider store={store}> */}
          <MyProvider>
            {children} {/* Render child components here */}
          </MyProvider>
          {/* </Provider> */}
        </body>
      </html>
      
  
    )
  }
  



//   import Demo from "@/components/Demo";
// import Hero from "@/components/Hero";


// export default function IndexPage() {
   
// return ( <div className="app flex flex-col items-center w-full">
//     <Hero  />
//     <Demo />
//   </div>
  
// )
//   }
  